version: '2'
services:
  jhipster6java11test-postgresql:
    image: postgres:11.2
    # volumes:
    #     - ~/volumes/jhipster/jHipster6Java11Test/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=jHipster6Java11Test
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
